version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL_OLD=http://localhost:8000
      - NEXT_PUBLIC_API_URL=https://q9i8zv2cu1.execute-api.us-east-1.amazonaws.com/mystage
      
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Removed the ports section from backend as it is not allowed in build context
