[tool.poetry]
name = "salesgpt-requirements"
version = "0.1.0"
description = ""
authors = ["chemik-bit <honza.michna.00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
langchain = "^0.0.340"
openai = "^1.3.5"
chromadb = "^0.4.18"
tiktoken = "^0.5.1"
pydantic = "^2.5.2"
litellm = "^1.7.5"
ipykernel = "^6.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
